live_config_reload = true

import = [
    "~/.config/alacritty/keybindings.toml"
]

[font]
normal = { family =  "FiraCode Nerd Font", style  = "Light" }
size = 13.0

[window]
decorations = "Full"
blur = true
opacity = 0.96

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
