brew install --cask macvim
brew install --cask slack
brew install --cask spectacle
brew install --cask flux
brew install --cask spotify
brew install --cask google-chrome
brew install --cask firefox
brew install --cask hammerspoon
brew install --cask alfred
brew install --cask anybar
brew install --cask chromium
brew install --cask figma

brew install --cask disk-inventory-x
brew install --cask dafuqtor/tap/midclick
brew install --cask keycastr
brew install --cask kap
brew install --cask signal
brew install --cask whatsapp
brew install --cask transmission
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoom
