
eval "$(starship init zsh)"

function set_win_title(){
    echo -ne "\033]0; $(basename "$PWD") \007"
}
precmd_functions+=(set_win_title)


for file in ~/.{functions,aliases,prompt,variables,bash_private,zsh_private,profile}; do
    [ -r "$file" ] && [ -f "$file" ] && source $file
done

# define alt+[arrows] to behave like bash
bindkey "^[b" backward-word
bindkey "^[f" forward-word

# for alacritty
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word



# Look up history with ctrl+R
bindkey '^R' history-incremental-search-backward


setopt GLOB_COMPLETE
setopt AUTO_CD

export EDITOR=vi
export GEDITOR=mvim
export GUI_EDITOR=nvim

HISTFILE=$$HOME/.zsh_history
SAVEHIST=5000
HISTSIZE=2000
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST
# do not store duplications
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

# not asking confirmation when !!
setopt NO_HIST_VERIFY


# terminal
export LSCOLORS=GxFxCxDxBxegedabagaced
export CLICOLOR=1

# node/nvm/npm

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/Users/ben/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# java
# export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"

[[ "$TERM_PROGRAM" == "CodeEditApp_Terminal" ]] && . "/Applications/CodeEdit.app/Contents/Resources/codeedit_shell_integration.zsh"

# homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
