
eval "$(starship init zsh)"

for file in ~/.{functions,aliases,prompt,variables,bash_private,zsh_private}; do
    [ -r "$file" ] && [ -f "$file" ] && source $file
done

# define alt+[arrows] to behave like bash
bindkey "^[b" backward-word
bindkey "^[f" forward-word


# Look up history with ctrl+R
bindkey '^R' history-incremental-search-backward


setopt GLOB_COMPLETE
setopt AUTO_CD

export EDITOR=vi
export GEDITOR=mvim

HISTFILE=$$HOME/.zsh_history
SAVEHIST=5000
HISTSIZE=2000
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST
# do not store duplications
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

# not asking confirmation when !!
setopt NO_HIST_VERIFY


# terminal
export LSCOLORS=GxFxCxDxBxegedabagaced
export CLICOLOR=1

# node/nvm/npm
export NVM_DIR="$HOME/.nvm"
export NVM_SYMLINK_CURRENT=false
[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/Users/ben/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"

# tmux
export DISABLE_AUTO_TITLE='true'
export PATH="$HOME/Library/Python/3.9/bin:$PATH"

# rust
[[ -s "$HOME/.cargo/env" ]] && source $HOME/.cargo/env

# python
eval "$(pyenv init -)"

# postgres with https://github.com/petere/homebrew-postgresql
# export PATH="/opt/homebrew/opt/postgresql@12/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@13/bin:$PATH"

# go
export GOPATH=$HOME/Code/gocode
export PATH=$PATH:$HOME/Code/gocode/bin
#ctags=/usr/local/bin/ctags

# ruby
#export PATH="/opt/homebrew/opt/ruby/bin:$HOME/.gem/ruby/3.0.0/bin:$PATH"
export PATH="/Users/ben/.rbenv/versions/3.1.3/bin:$PATH"
eval "$(rbenv init - zsh)"

# flutter
export PATH="$PATH:$HOME/Work/flutter/bin"

# fzf fuzzy finder file
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"
export FZF_DEFAULT_COMMAND="fd --type f"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# auto completion
fpath=(~/Code/dotfiles/zsh/functions $fpath)

if type brew &>/dev/null
then
    fpath=("$(brew --prefix)/share/zsh/site-functions" $fpath)
fi

autoload -Uz compinit && compinit

# gpg passphrase
export GPG_TTY=$(tty)

export PATH="$PATH:$HOME/Code/dotfiles/bin"

export PATH="$HOME/.local/bin:$PATH"

[ -f "/opt/homebrew/opt/vasy/lib/vasy.sh" ] && source "/opt/homebrew/opt/vasy/lib/vasy.sh" ]
export PATH="/opt/homebrew/opt/postgresql@13/bin:$PATH"



# pnpm
export PNPM_HOME="/Users/ben/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# java
export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
# /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
