for file in ~/.{functions,aliases,variables,prompt,bash_private}; do
    [ -r "$file" ] && [ -f "$file" ] && source $file
done
unset file

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export EDITOR=vi
export GEDITOR=mvim

# Python
export PYTHONSTARTUP=~/.pythonstartup

# virtualenvwrapper
export WORKON_HOME=~/.env/
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export PIP_RESPECT_VIRTUALENV=true
[[ -s "/usr/local/bin/virtualenvwrapper.sh" ]] && source /usr/local/bin/virtualenvwrapper.sh

[[ -s "~/.profile" ]] && source ~/.profile

# git
export GIT_MERGE_AUTOEDIT=no

# history
export HISTTIMEFORMAT="%Y-%m-%d %H:%M "
export HISTFILESIZE=2000
export HISTCONTROL=ignoreboth:erasedups
export PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
shopt -s histappend

# MySQL
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/:$DYLD_LIBRARY_PATH

# PATH
PATH=$PATH:/usr/local/mysql/bin
PATH=$PATH:/usr/local/mongo/bin
PATH=$PATH:/usr/local/bin
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/local/redis/bin
PATH=$PATH:$HOME/Code/bin
PATH=$PATH:$HOME/Code/gocode/bin
PATH=$PATH:/usr/local/bin/google-cloud-sdk/bin
PATH=$PATH:$HOME/Code/on-wifi/actions
export PATH

### Added by the Heroku Toolbelt
export GREP_OPTIONS='--color=auto'

export NVM_DIR="$HOME/.nvm"
export NVM_SYMLINK_CURRENT=false

[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
export GOPATH="$HOME/go"
[[ -s "$HOME/Code/git-push-my-face/.env" ]] && source ~/Code/git-push-my-face/.env
[[ -s "$HOME/.git-completion" ]] && source ~/.git-completion
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export PATH="$HOME/.cargo/bin:$PATH"

export LDFLAGS="-L/usr/local/opt/openssl/lib"
